### ISSUE TITLE
Add validations to the color input

### ISSUE THREAD

**Issue by radiovisual** [radiovisual/github-tweaks#5]
Right now whatever value you assign in the options is set on the global stylesheet. ideally it would be nice if there was some sort of validation to ensure only valid HTML and CSS values are used.

Can use https://github.com/radiovisual/html-colors to help with the color validations.

## TODO:

- [ ] Don't require the `#` in the css.
- [ ] Prepend a `#` to all hex color values if not present
- [ ] Allow [HTML/CSS color names](https://github.com/radiovisual/html-colors)
- [ ] Don't allow invalid color names or color values
- [ ] Highlight the input field red to alert the user something is wrong

To get started, you could do something like:

```js
const htmlColors = require('html-colors');

function isHexColor(string) {
  const clean = string.trim().toLowerCase().replace(/^#/, '');
  if (isHTMLColor(clean) || isReservedColorWord(clean)) {
	return true;
  }

  const reg = /^[0-9A-F]{3}$|^[0-9A-F]{6}$/i;
  return reg.test(clean);
}

function isHTMLColor(string) {
  const colors = htmlColors.names();
  return colors.indexOf(string.toLowerCase()) > -1;
}

function isReservedColorWord(string) {
  const reservedColorWords = ['initial', 'inherit'];
  return reservedColorWords.indexOf(string) > -1;
}
```

Then in `options.js`:

```js
function saveOptions() {
	const urlColor = urlColorInput.value;

	if (window.isHTMLColor(urlColor)) {
		urlColorInput.classList.remove('inputError');
		window.GitHubTweaks.storage.set({urlColor});
	} else {
		urlColorInput.classList.add('inputError');
	}
}
```
